x-hades-environment: &hades_environment
  SECRET_KEY: ${SECRET_KEY}
  CELERY_BROKER_URL: "redis://redis:6379/0"
  RESULT_BACKEND: "redis://redis:6379/0"
  REDIS_URL: "redis://redis:6379/0"
  MAIL_SERVER: ${MAIL_SERVER}
  MAIL_PORT: ${MAIL_PORT}
  MAIL_USERNAME: ${MAIL_USERNAME}
  MAIL_PASSWORD: ${MAIL_PASSWORD}
  DATABASE_URI: "sqlite:////app/storage/database/hades.db"

services:
  web:
    build: .
    image: hades:latest
    command: gunicorn -b "0.0.0.0:8000" -k gevent --workers 1 --threads 2 'app:create_app()' --reload
    volumes:
      - .:/app
      - ./app/storage:/app/storage
    depends_on:
      - redis
    restart: always
    environment:
      <<: *hades_environment
  worker:
    build: .
    image: hades:latest
    command: celery -A app.celery worker --loglevel=info --pool=solo --hostname=worker@%h
    volumes:
      - .:/app
      - ./app/storage:/app/storage
    depends_on:
      - redis
    restart: always
    environment:
      <<: *hades_environment
  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./app/storage/redis:/data
    restart: always
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    restart: always